CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255),
  sku VARCHAR(255) NOT NULL UNIQUE,
  image_url VARCHAR(255),
  description TEXT,
  quantity INT DEFAULT 0,
  price DECIMAL(10,2) NOT NULL
);